<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            ['name' => 'ジョブズ',
            'email' => 'user1@example.com',
            'sex' => '0',
            'self_introduction' => 'ジョブズです',
            'img_name' => 'sample001.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'ザッカーバーグ',
            'email' => 'user2@example.com',
            'sex' => '1',
            'self_introduction' => 'ザッカーバーグです',
            'img_name' => 'sample002.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'ジェフペゾフ',
            'email' => 'user3@example.com',
            'sex' => '0',
            'self_introduction' => 'ジェフですです',
            'img_name' => 'sample003.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'イーロン',
            'email' => 'user4@example.com',
            'sex' => '0',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample004.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'サンプル５',
            'email' => 'user5@example.com',
            'sex' => '1',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample5.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'サンプル６',
            'email' => 'user6@example.com',
            'sex' => '1',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample6.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'サンプル７',
            'email' => 'user7@example.com',
            'sex' => '1',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample7.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'サンプル８',
            'email' => 'user8@example.com',
            'sex' => '1',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample8.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'サンプル９',
            'email' => 'user9@example.com',
            'sex' => '1',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample9.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'サンプル１０',
            'email' => 'user10@example.com',
            'sex' => '0',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample10.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'サンプル１１',
            'email' => 'user11@example.com',
            'sex' => '0',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample11.jpg',
            'password' => Hash::make('password123'),
            ],
            ['name' => 'サンプル１２',
            'email' => 'user12@example.com',
            'sex' => '0',
            'self_introduction' => 'イーロンです',
            'img_name' => 'sample12.jpg',
            'password' => Hash::make('password123'),
            ],
        ]);
    }
}
